### ISSUE TITLE
write が Python3 に対応していない

### ISSUE THREAD

**Issue by ysibata** [vippool/storage#8]
Python 3.7.4 にて、sample.py をもとに write を試すと以下のようにエラーが発生します。

```
>>> print( vs1.write( '...', 0.01 ) )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "storage-master/vippool/storage.py", line 523, in write
    return self.newtx( self.address(), value, fee, data )
  File "storage-master/vippool/storage.py", line 496, in newtx
    params['data'] = hexlify( data ).decode('UTF-8')
TypeError: a bytes-like object is required, not 'str'
```

事前に byte列に変換することで問題が回避できることは確認しました。

```
>>> print( vs1.write( '...'.encode(), 0.01 ) )
8abb8ed0b75435437f676313eb80673811641...
```

また、read についても文字列として受け取りたい場合には、decodeが必要になります。

```
>>> print( vs1.read( '8abb8ed0b75435437f676313eb80673811641...' ) )
b'...'
>>> print( vs1.read( '8abb8ed0b75435437f676313eb80673811641...' ).decode() )
...
```

**Comment by hoshizuki** [comment]
これも Python2 と 3 の非互換な部分ですね。
何かいい書き方がないか調べておきます。
